# Minimal pyproject.toml for editable install
[project]
name = "dqix"
version = "0.1.0"
description = "Domain Quality Index CLI and library"
requires-python = ">=3.9"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["dqix"]
