apiVersion: v1
kind: Service
metadata:
  name: dqix-service
  namespace: dqix
  labels:
    app: dqix
    app.kubernetes.io/name: dqix
    app.kubernetes.io/version: "1.2.0"
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: dqix-platform
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: dqix
---
apiVersion: v1
kind: Service
metadata:
  name: dqix-loadbalancer
  namespace: dqix
  labels:
    app: dqix
    app.kubernetes.io/name: dqix
    app.kubernetes.io/version: "1.2.0"
    app.kubernetes.io/component: loadbalancer
    app.kubernetes.io/part-of: dqix-platform
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 443
    targetPort: 8443
    protocol: TCP
    name: https
  selector:
    app: dqix 