# Perfect Security Configuration Template
# Based on analysis of top-performing security websites
# Target: 95%+ DQIX Security Score

# DNS Configuration
dns:
  # Email Security (Critical - 30% of security score)
  spf_record: |
    v=spf1 include:mailgun.org include:sendgrid.net -all
    # Use -all for strict policy, ~all for soft-fail
    # Include only trusted email providers
  
  dmarc_record: |
    v=DMARC1; p=reject; pct=100; 
    rua=mailto:dmarc-reports@yourdomain.com; 
    ruf=mailto:dmarc-forensic@yourdomain.com; 
    aspf=r; adkim=r
    # p=reject for maximum security
    # pct=100 for full enforcement
    # Include reporting addresses
  
  dkim_configuration:
    selector: "default"
    key_size: 2048  # Minimum RSA-2048
    algorithm: "rsa-sha256"
    
  # DNS Security
  dnssec: enabled
  
  caa_records:
    - "0 issue \"letsencrypt.org\""
    - "0 issue \"digicert.com\""
    - "0 issuewild \"letsencrypt.org\""
    - "0 iodef \"mailto:security@yourdomain.com\""

# TLS/SSL Configuration
tls:
  # Certificate Management
  certificate:
    provider: "Let's Encrypt"  # Free, automated
    key_size: 2048
    signature_algorithm: "SHA-256"
    validity_period: 90  # Auto-renewal
    
  # Protocol Configuration
  protocols:
    tls_1_3: enabled
    tls_1_2: enabled
    tls_1_1: disabled
    tls_1_0: disabled
    ssl_3_0: disabled
    
  # Cipher Suites (Modern configuration)
  ciphers:
    - "TLS_AES_256_GCM_SHA384"
    - "TLS_CHACHA20_POLY1305_SHA256"
    - "TLS_AES_128_GCM_SHA256"
    - "ECDHE-ECDSA-AES256-GCM-SHA384"
    - "ECDHE-RSA-AES256-GCM-SHA384"

# HTTP Security Headers
security_headers:
  # HSTS (HTTP Strict Transport Security)
  strict_transport_security:
    max_age: 31536000  # 1 year
    include_subdomains: true
    preload: true
    
  # Content Security Policy (Critical)
  content_security_policy: |
    default-src 'none';
    script-src 'self' 'nonce-{RANDOM_NONCE}';
    style-src 'self' 'unsafe-inline';
    img-src 'self' data: https:;
    font-src 'self';
    connect-src 'self';
    frame-ancestors 'none';
    base-uri 'self';
    form-action 'self';
    upgrade-insecure-requests;
    report-uri https://reports.yourdomain.com/csp
    
  # Frame Protection
  x_frame_options: "DENY"
  
  # Content Type Protection
  x_content_type_options: "nosniff"
  
  # XSS Protection (Legacy support)
  x_xss_protection: "1; mode=block"
  
  # Referrer Policy
  referrer_policy: "strict-origin-when-cross-origin"
  
  # Permissions Policy
  permissions_policy: |
    accelerometer=(), camera=(), geolocation=(), 
    gyroscope=(), magnetometer=(), microphone=(), 
    payment=(), usb=(), interest-cohort=()

# HTTPS Implementation
https:
  # Redirect Configuration
  http_redirect:
    status_code: 301  # Permanent redirect
    target: "https://yourdomain.com"
    
  # Performance Targets
  response_time:
    target: 500  # milliseconds
    acceptable: 1000  # milliseconds
    
  # HTTP/2 Support
  http2: enabled
  
  # OCSP Stapling
  ocsp_stapling: enabled

# Server Configuration
server:
  # Hide Server Information
  server_header: false  # Don't expose server type
  x_powered_by: false   # Don't expose technology stack
  
  # Security Features
  security_txt: |
    Contact: security@yourdomain.com
    Expires: 2025-12-31T23:59:59.000Z
    Encryption: https://yourdomain.com/pgp-key.txt
    Preferred-Languages: en, th
    Canonical: https://yourdomain.com/.well-known/security.txt

# Implementation Costs (Affordable)
cost_analysis:
  ssl_certificate: "Free (Let's Encrypt)"
  dns_hosting: "$5-20/month (Cloudflare, Route53)"
  cdn_security: "Free tier available (Cloudflare)"
  monitoring: "Free tier available (UptimeRobot)"
  total_monthly: "$5-30"

# Implementation Tools (Open Source)
tools:
  certificate_management:
    - "Certbot (Let's Encrypt client)"
    - "acme.sh (ACME client)"
    
  web_server:
    - "Nginx with security modules"
    - "Apache with mod_security"
    
  monitoring:
    - "SSL Labs API"
    - "Mozilla Observatory API"
    - "securityheaders.com API"
    
  dns_management:
    - "Cloudflare API"
    - "Route53 CLI"

# Verification Commands
verification:
  dns_check: |
    dig TXT yourdomain.com
    dig TXT _dmarc.yourdomain.com
    dig CAA yourdomain.com
    
  ssl_check: |
    curl -I https://yourdomain.com
    openssl s_client -connect yourdomain.com:443 -servername yourdomain.com
    
  security_headers: |
    curl -I https://yourdomain.com
    # Check for all security headers
    
  dqix_assessment: |
    python -m dqix assess yourdomain.com --comprehensive

# Expected DQIX Scores
expected_scores:
  tls_security: 1.00      # Perfect TLS configuration
  dns_security: 0.95      # Near-perfect with all features
  security_headers: 0.95  # Comprehensive header suite
  https_implementation: 1.00  # Perfect HTTPS setup
  overall_security: 0.97  # 97% security score
  overall_dqix: 0.95      # 95% overall score (A+ grade)

# Maintenance Schedule
maintenance:
  certificate_renewal: "Automated (90 days)"
  security_review: "Monthly"
  dqix_assessment: "Weekly"
  vulnerability_scan: "Monthly"
  
# Compliance Standards Met
compliance:
  - "OWASP Top 10 (2021)"
  - "Mozilla Observatory A+"
  - "SSL Labs A+"
  - "Google PageSpeed Security"
  - "NIST Cybersecurity Framework" 